site_name: Heart Stroke Risk Stratification Platform Docs
site_url: https://github.com/Rahul-404/heart-stroke-risk-stratification/
site_description: >
  Analyze patient demographics, clinical data, and lifestyle habits to calculate stroke probability
  and classify individuals into specific clinical risk levels for better preventative care.

repo_url: https://github.com/Rahul-404/heart-stroke-risk-stratification
repo_name: heart-stroke-risk-stratification

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/git-alt
    logo: fontawesome/solid/r
    favicons: assets/favicon.ico
  language: en
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode


nav:
  - Home: index.md

  - Getting Started:
      - Local Setup: 00_getting_started/local_setup.md

  - Problem Framing:
      - Overview: 01_problem/problem_statement.md
      - Success Criteria: 01_problem/success_criteria.md

  - Data Foundation:
      - Data Overview: 02_data/data_overview.md
      - Data Schema: 02_data/schema.md
      - Data Quality & Bias: 02_data/data_quality.md
      - Data Validation Rules: 02_data/data_validation.md

  - Feature Engineering:
      - Feature Engineering Overview: 03_features/feature_engineering.md
      - Missing Data Strategy: 03_features/missing_data.md
      - Encoding & Normalization: 03_features/encoding.md

  - Modeling:
      - Experiment Tracking: 04_modeling/experiments.md
      - Evaluation Metrics: 04_modeling/evaluation.md
      - Model Card: 04_modeling/model_card.md

  - System Design:
      - Architecture Overview: 05_system/architecture.md
      - Inference Flow: 05_system/inference.md
      - API Specification: 05_system/api_spec.md

  - Reliability & Quality:
      - Testing Strategy: 06_quality/testing_strategy.md
      - Monitoring & Drift: 06_quality/monitoring.md

  - Governance:
      - Risks & Ethics: 07_governance/risks.md
      - Roadmap: 07_governance/roadmap.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy                # or numpy, auto, google, sphinx
            allow_inspection: true
            find_stubs_package: false
            heading_level: 3                      # starting header level
            parameter_headings: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            type_parameter_headings: false
            show_labels: false
            show_submodules: true
            extra:                                 # move all unrecognized/deprecated options here
              ignore_init_summary: true
              inheritance_diagram_direction: LR
              trim_doctest_flags: true

  - social:
      cards_layout_options:
        background_color: "#ff1493"

  - autorefs:
      link_titles: auto

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      default_lang: python

extra_javascript:
- https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rahulshelke981/
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/Rahul-404
      name: Github
    # - icon: fontawesome/brands/kaggle
    #   link: https://www.kaggle.com/rahulshelke98
    #   name: Kaggle
    # - icon: simple/medium
    #   link: https://medium.com/@rahulshelke3399
    #   name: Medium

  generator: false

copyright: Copyright &copy; 2026 Rahul Shelke
